<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0"
	total="3" passed="2">
	<reporter-output>
	</reporter-output>
	<suite name="Default suite" duration-ms="34"
		started-at="2020-05-06T13:45:27 CST"
		finished-at="2020-05-06T13:45:27 CST">
		<groups>
		</groups>
		<test name="Default test" duration-ms="34"
			started-at="2020-05-06T13:45:27 CST"
			finished-at="2020-05-06T13:45:27 CST">
			<class name="com.webtest.core.Test1">
				<test-method status="PASS"
					signature="addListener(org.testng.ITestContext)[pri:0, instance:com.webtest.core.Test1@6ddf90b0]"
					name="addListener" is-config="true" duration-ms="11"
					started-at="2020-05-06T13:45:27 CST"
					finished-at="2020-05-06T13:45:27 CST">
					<params>
						<param index="0">
							<value>
                <![CDATA[org.testng.TestRunner@376b4233]]>
							</value>
						</param>
					</params>
					<reporter-output>
					</reporter-output>
				</test-method> <!-- addListener -->
				<test-method status="PASS"
					signature="test1()[pri:0, instance:com.webtest.core.Test1@6ddf90b0]"
					name="test1" duration-ms="6" started-at="2020-05-06T13:45:27 CST"
					finished-at="2020-05-06T13:45:27 CST">
					<reporter-output>
					</reporter-output>
				</test-method> <!-- test1 -->
				<test-method status="PASS"
					signature="test2()[pri:0, instance:com.webtest.core.Test1@6ddf90b0]"
					name="test2" duration-ms="2" started-at="2020-05-06T13:45:27 CST"
					finished-at="2020-05-06T13:45:27 CST">
					<reporter-output>
					</reporter-output>
				</test-method> <!-- test2 -->
				<test-method status="FAIL"
					signature="test3()[pri:0, instance:com.webtest.core.Test1@6ddf90b0]"
					name="test3" duration-ms="2" started-at="2020-05-06T13:45:27 CST"
					finished-at="2020-05-06T13:45:27 CST">
					<exception class="java.lang.AssertionError">
						<message>
              <![CDATA[expected [1] but found [2]]]>
						</message>
						<full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [1] but found [2]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at com.webtest.core.Test1.test3(Test1.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
						</full-stacktrace>
					</exception> <!-- java.lang.AssertionError -->
					<reporter-output>
					</reporter-output>
				</test-method> <!-- test3 -->
			</class> <!-- com.webtest.core.Test1 -->
		</test> <!-- Default test -->
	</suite> <!-- Default suite -->
</testng-results>
