<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-DDFJPIK8" ignored="0" name="Test" tests="5" failures="2" timestamp="2020-11-13T14:25:02 CST" time="0.885" errors="0">
  <testcase name="Test1" time="0.008" classname="com.bxx.test.allTest"/>
  <testcase name="Test2" time="0.002" classname="com.bxx.test.allTest"/>
  <testcase name="Test3" time="0.002" classname="com.bxx.test.allTest">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at com.bxx.test.allTest.Test3(allTest.java:61)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Test3 -->
  <testcase name="Test4" time="0.002" classname="com.bxx.test.allTest">
    <failure type="java.lang.AssertionError" message="expected [3] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [1]
at com.bxx.test.allTest.Test4(allTest.java:66)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Test4 -->
  <testcase name="Test5" time="0.001" classname="com.bxx.test.allTest"/>
</testsuite> <!-- Test -->
